/**
 * weekly-review.ts
 *
 * Docker script — runs every Sunday morning at 7:00am via Ofelia,
 * BEFORE calendar-reminder.ts fires at 8:00am.
 *
 * What it does:
 *   1. Fetches completed Notion tasks for the past week
 *   2. Fetches all calendar events for the past week
 *   3. Sends both to local Ollama for a prose weekly review
 *   4. Writes the review to Obsidian: Weekly Reviews/YYYY-MM-DD.md
 *
 * Schedule (set in docker-compose.yml labels):
 *   0 7 * * 0   (7:00am every Sunday)
 *
 * Requirements:
 *   - Ollama running on host: ollama serve
 *   - Model pulled: ollama pull llama3.2:3b
 */

import * as dotenv from "dotenv";
import * as path from "path";
dotenv.config({ path: path.resolve(__dirname, "../../.env") });

import { getCompletedTasksForWeek, listTasks, formatTaskList } from "../tools/notion";
import { getWeekSummary } from "../tools/calendar";
import { writeWeeklyReview } from "../tools/obsidian";
import { callOllama, checkOllamaAvailable } from "../lib/ollama";

// ── Config ──────────────────────────────────────────────────────────────────

const PROFILE = "personal" as const;

// ── Helpers ─────────────────────────────────────────────────────────────────

function todayISO(): string {
  return new Date().toISOString().split("T")[0];
}

function getThisMonday(): string {
  const d = new Date();
  const day = d.getDay();
  const monday = new Date(d);
  monday.setDate(d.getDate() - ((day + 6) % 7));
  return monday.toISOString().split("T")[0];
}

function addDays(dateStr: string, days: number): string {
  const d = new Date(dateStr);
  d.setDate(d.getDate() + days);
  return d.toISOString().split("T")[0];
}

function formatDateRange(start: string, end: string): string {
  const s = new Date(start);
  const e = new Date(end);
  return (
    s.toLocaleDateString("en-US", { month: "long", day: "numeric" }) +
    " – " +
    e.toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })
  );
}

function buildCalendarText(summary: Awaited<ReturnType<typeof getWeekSummary>>): string {
  if (summary.events.length === 0) return "No events scheduled this week.";
  const lines: string[] = [];
  for (const day of summary.byDay) {
    if (day.events.length === 0) continue;
    lines.push(`${day.dayName} ${day.date}:`);
    for (const e of day.events) {
      const time = e.isAllDay
        ? "All day"
        : new Date(e.start).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit", hour12: true });
      lines.push(`  • [${e.calendarName}] ${e.summary} at ${time}`);
    }
  }
  return lines.join("\n");
}

// ── Ollama review generation ─────────────────────────────────────────────────

async function generateWeeklyReview(
  completedText: string,
  incompleteText: string,
  calendarText: string,
  weekRange: string
): Promise<string> {
  const context = [
    `WEEK: ${weekRange}`,
    ``,
    `=== COMPLETED TASKS ===`,
    completedText,
    ``,
    `=== INCOMPLETE / CARRIED OVER TASKS ===`,
    incompleteText,
    ``,
    `=== CALENDAR EVENTS THIS WEEK ===`,
    calendarText,
  ].join("\n");

  return callOllama(context, {
    systemPrompt: [
      `You are writing a personal weekly review for the week of ${weekRange}.`,
      `Based on the completed tasks, incomplete tasks, and calendar events provided:`,
      ``,
      `1. Write a brief narrative of what was accomplished this week (2-3 sentences).`,
      `2. Highlight any wins or notable completions.`,
      `3. Note patterns — were certain categories neglected? Was the week overloaded?`,
      `4. For incomplete tasks, briefly note what carried over and why it might have been missed.`,
      `5. End with 1-2 focus suggestions for next week.`,
      ``,
      `Write in a personal, reflective tone. Use markdown headers (##). Keep it under 400 words.`,
      `Only reference what is in the data provided — do not invent information.`,
    ].join("\n"),
    maxTokens: 700,
    temperature: 0.4,
  });
}

// ── Build Obsidian note ──────────────────────────────────────────────────────

function buildNote(
  review: string,
  completedText: string,
  incompleteText: string,
  calendarText: string,
  weekStart: string,
  weekEnd: string
): string {
  const now = new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
  const range = formatDateRange(weekStart, weekEnd);

  return [
    `# Weekly Review`,
    `**${range}**`,
    ``,
    `---`,
    ``,
    `## Review`,
    ``,
    review,
    ``,
    `---`,
    ``,
    `## Completed Tasks`,
    ``,
    "```",
    completedText,
    "```",
    ``,
    `## Incomplete / Carried Over`,
    ``,
    "```",
    incompleteText,
    "```",
    ``,
    `## Calendar This Week`,
    ``,
    "```",
    calendarText,
    "```",
    ``,
    `---`,
    `*Generated by Personal MCP at ${now} on ${todayISO()}*`,
  ].join("\n");
}

// ── Main ─────────────────────────────────────────────────────────────────────

async function main() {
  const weekStart = getThisMonday();
  const weekEnd   = addDays(weekStart, 7);
  const weekRange = formatDateRange(weekStart, weekEnd);

  console.log(`\nWeekly Review — ${weekRange}\n`);

  // Fail fast if Ollama is not available
  console.log("Checking Ollama...");
  try {
    await checkOllamaAvailable();
    console.log("  ✅ Ollama ready\n");
  } catch (err) {
    console.error(`  ❌ ${err}`);
    process.exit(1);
  }

  // ── Step 1: Completed tasks ──────────────────────────────────────────────
  console.log("Fetching completed tasks...");
  let completedText = "";
  try {
    const completed = await getCompletedTasksForWeek(weekStart, weekEnd, PROFILE);
    completedText = completed.length > 0
      ? formatTaskList(completed, `Completed (${completed.length})`)
      : "No completed tasks found for this week.";
    console.log(`  ✅ ${completed.length} completed task(s)`);
  } catch (err) {
    console.error("  ❌ Failed to fetch completed tasks:", err);
    completedText = "Could not fetch completed tasks.";
  }

  // ── Step 2: Incomplete tasks ─────────────────────────────────────────────
  console.log("Fetching incomplete tasks...");
  let incompleteText = "";
  try {
    const incomplete = await listTasks(PROFILE, { showCompleted: false });
    incompleteText = incomplete.length > 0
      ? formatTaskList(incomplete, `Incomplete (${incomplete.length})`)
      : "No incomplete tasks.";
    console.log(`  ✅ ${incomplete.length} incomplete task(s)`);
  } catch (err) {
    console.error("  ❌ Failed to fetch incomplete tasks:", err);
    incompleteText = "Could not fetch incomplete tasks.";
  }

  // ── Step 3: Calendar events ──────────────────────────────────────────────
  console.log("Fetching calendar events...");
  let calendarText = "";
  try {
    const summary = await getWeekSummary(PROFILE, weekStart);
    calendarText = buildCalendarText(summary);
    console.log(`  ✅ ${summary.events.length} event(s) this week`);
  } catch (err) {
    console.error("  ❌ Failed to fetch calendar events:", err);
    calendarText = "Could not fetch calendar events.";
  }

  // ── Step 4: Generate review with Ollama ──────────────────────────────────
  console.log("Generating weekly review with Ollama...");
  let review = "";
  try {
    review = await generateWeeklyReview(completedText, incompleteText, calendarText, weekRange);
    console.log("  ✅ Review generated");
  } catch (err) {
    console.error("  ❌ Ollama failed:", err);
    review = "*AI review generation failed — check Ollama logs.*";
  }

  // ── Step 5: Write to Obsidian ─────────────────────────────────────────────
  const noteContent = buildNote(review, completedText, incompleteText, calendarText, weekStart, weekEnd);

  console.log(`\nWriting to Obsidian: Weekly Reviews/${weekStart}.md`);
  try {
    const result = await writeWeeklyReview(weekStart, noteContent, PROFILE);
    console.log(result);
  } catch (err) {
    console.error("❌ Failed to write to Obsidian:", err);
    console.log("\n── FALLBACK OUTPUT ──\n");
    console.log(noteContent);
  }

  console.log("\nDone.");
  process.exit(0);
}

main().catch((err) => {
  console.error("Fatal error:", err);
  process.exit(1);
});